add requests in requires
File "/usr/local/lib/python3.6/site-packages/libvin/nhtsa.py", line 9, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'